version: '3.8'
services:
  server:
    build: .
    image: filmorate-server
    container_name: filmorate-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/filmorate
      - SPRING_DATASOURCE_USERNAME=filmorate
      - SPRING_DATASOURCE_PASSWORD=filmorate
      - TZ=Europe/Moscow

  db:
    image: postgres:14-alpine
    container_name: filmorate-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=filmorate
      - POSTGRES_USER=filmorate
      - POSTGRES_DB=filmorate
      - TZ=Europe/Moscow
